USER_NAME_FIELD = '//*[@id="user-name"]'
USER_PASSWORD_FIELD = '//*[@id="password"]'
LOGIN_BUTTON = '//*[@id="login-button"]'
LOGIN_ERROR = 'h3[data-test="error"]'
ADD_BIKE_ITEM = '//*[@id="add-to-cart-sauce-labs-bike-light"]'
CART_BADGE_LOCATOR = 'shopping_cart_badge'
CART_LINK = 'shopping_cart_link'
REMOVE_BIKE_FROM_THE_CART = 'remove-sauce-labs-bike-light'
REMOVED_ITEM = 'removed_cart_item'
ADD_ITEM_4 = 'item_4_img_link'
BUTTON_ADD = 'add-to-cart'
ITEM = 'inventory_item_img'
REMOVE = 'remove'
ADD_ITEM_2_BY_TITLE = 'item_2_title_link'
DROPDOWN_MENU = 'product_sort_container'
FIND_PRODUCTS_IN_DD = 'inventory_item_label'
FIND_PRICES_IN_DD = 'inventory_item_price'

